// ─────────────────────────────────────────────
// 报告构建：Email HTML / Slack blocks
// Ported from daily_report.py build_email_html / send_slack
// ─────────────────────────────────────────────
import { DiscrepancyRow, DspSummaryRow, DISCREPANCY_CONFIG } from './types';
import { fmtNum, fmtPct } from './dataProcessor';

const th = DISCREPANCY_CONFIG.highlightThreshold * 100;

export function buildEmailSubject(dateLabel: string, highlightCount: number): string {
  return highlightCount > 0
    ? `⚠️ GCK publisher discrepancy alert — ${dateLabel} (${highlightCount} highlights)`
    : `✅ GCK publisher discrepancy alert — ${dateLabel} (All Clear)`;
}

const esc = (s: unknown): string =>
  String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

type Col<T> = [key: keyof T, label: string, kind: 'text' | 'num' | 'pct'];

function tableHtml<T extends Record<string, any>>(data: T[], cols: Col<T>[], highlight = false): string {
  if (!data.length) return '<p><i>No data available for this section.</i></p>';
  const header = cols.map(([, label]) => `<th>${label}</th>`).join('');
  const body = data.map((row) => {
    const cells = cols.map(([key, , kind]) => {
      const v = row[key];
      if (v === null || v === undefined) return '<td>N/A</td>';
      if (kind === 'num') return `<td>${fmtNum(v as number)}</td>`;
      if (kind === 'pct') return `<td>${fmtPct(v as number)}</td>`;
      return `<td>${esc(v)}</td>`;
    }).join('');
    return `<tr style="background:${highlight ? '#fff3cd' : 'white'}">${cells}</tr>`;
  }).join('');
  return `<table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse;width:100%;font-size:13px"><thead style="background:#1976d2;color:white"><tr>${header}</tr></thead><tbody>${body}</tbody></table>`;
}

const DSP_SUMMARY_COLS: Col<DspSummaryRow>[] = [
  ['dsp', 'DSP', 'text'],
  ['publishers', 'Publishers', 'num'],
  ['rows', 'Rows', 'num'],
  ['pubmaticSpend', 'PubMatic Spend', 'num'],
  ['dspSpend', 'DSP Spend', 'num'],
  ['spendDiscrepancyPct', 'Spend Discrepancy', 'pct'],
  ['pubmaticImps', 'PubMatic Imps', 'num'],
  ['dspImps', 'DSP Imps', 'num'],
  ['discrepancyRate', 'Imps Discrepancy', 'pct'],
];

const DETAIL_COLS: Col<DiscrepancyRow>[] = [
  ['publisherId', 'Publisher ID', 'text'],
  ['publisherName', 'Publisher', 'text'],
  ['dsp', 'DSP', 'text'],
  ['pubmaticSpend', 'PubMatic Spend', 'num'],
  ['dspSpend', 'DSP Spend', 'num'],
  ['spendDiscrepancyPct', 'Spend Discrepancy', 'pct'],
  ['pubmaticImps', 'PubMatic Imps', 'num'],
  ['dspImps', 'DSP Imps', 'num'],
  ['discrepancyRate', 'Imps Discrepancy', 'pct'],
];

export function buildEmailHtml(
  rows: DiscrepancyRow[],
  summaryText: string,
  dateLabel: string,
  dspSummary: DspSummaryRow[],
  topSpenders: DiscrepancyRow[],
  highlights: DiscrepancyRow[]
): string {
  const highlightSection = highlights.length
    ? tableHtml(highlights, DETAIL_COLS, true)
    : '<p>✅ No publisher/DSP combinations exceed the ±5% Spend or Impressions Discrepancy threshold.</p>';

  const publishers = new Set(rows.map((r) => r.publisherId)).size;
  const dsps = new Set(rows.map((r) => r.dsp)).size;
  const now = new Date().toISOString().slice(0, 16).replace('T', ' ');

  return `
    <html>
    <body style="font-family:Arial,sans-serif;max-width:1100px;margin:auto;color:#333">
    <h2>📊 PubMatic Daily Discrepancy Report — ${dateLabel}</h2>
    <p>
        <b>Report generated:</b> ${now} UTC<br>
        <b>Publishers monitored:</b> ${publishers} &nbsp;|&nbsp;
        <b>DSPs:</b> ${dsps} &nbsp;|&nbsp;
        <b>Rows:</b> ${rows.length} &nbsp;|&nbsp;
        <b>Highlight threshold:</b> ±${th.toFixed(0)}% Spend or Impressions Discrepancy
    </p>
    <hr>
    <h3>Executive Summary</h3>
    <p style="background:#f5f5f5;padding:14px;border-left:4px solid #1976d2;font-size:13px;line-height:1.7;white-space:pre-line">${esc(summaryText).replace(/\n/g, '<br>')}</p>

    <h3>📊 Section 1 — Overall DSP Summary (All Publishers Combined)</h3>
    <p>Aggregated team-wide view by DSP.</p>
    ${tableHtml(dspSummary, DSP_SUMMARY_COLS)}

    <h3>📋 Section 2 — Top 20 Spenders by DSP Partner Spend</h3>
    <p>The 20 publisher/DSP combinations with the highest DSP Partner Spend.</p>
    ${tableHtml(topSpenders, DETAIL_COLS)}

    <h3 style="color:#d32f2f">⚠️ Section 3 — Highlighted Publisher / DSP</h3>
    <p>Spend Discrepancy or Impressions Discrepancy > ±${th.toFixed(0)}%.</p>
    ${highlightSection}

    <br>
    <p style="color:#999;font-size:11px">Auto-generated by GCK Automation — Discrepancy Check-in</p>
    </body>
    </html>
  `;
}

export function buildSlackBlocks(
  rows: DiscrepancyRow[],
  summaryText: string,
  dateLabel: string,
  dspSummary: DspSummaryRow[],
  topSpenders: DiscrepancyRow[],
  highlights: DiscrepancyRow[]
): object[] {
  const hasHighlights = highlights.length > 0;
  const headerText = hasHighlights
    ? `⚠️ *PubMatic Discrepancy Alert — ${dateLabel}*\n${highlights.length} publisher/DSP combos exceed ±${th.toFixed(0)}% Spend or Impressions Discrepancy`
    : `✅ *PubMatic Discrepancy Report — ${dateLabel}*\nAll publishers within threshold`;

  const blocks: object[] = [
    { type: 'header', text: { type: 'plain_text', text: `PubMatic Discrepancy Report — ${dateLabel}` } },
    { type: 'section', text: { type: 'mrkdwn', text: headerText } },
    { type: 'divider' },
    { type: 'section', text: { type: 'mrkdwn', text: `*🤖 Summary*\n${summaryText.slice(0, 2500)}` } },
  ];

  if (dspSummary.length) {
    const lines = dspSummary.slice(0, 5).map((r) =>
      `• ${r.dsp} — Spend ${fmtPct(r.spendDiscrepancyPct)} (PM $${Math.round(r.pubmaticSpend).toLocaleString()} vs DSP $${Math.round(r.dspSpend).toLocaleString()})`);
    blocks.push({ type: 'divider' });
    blocks.push({ type: 'section', text: { type: 'mrkdwn', text: '📊 *Top DSPs by Spend Discrepancy*\n' + lines.join('\n') } });
  }

  if (topSpenders.length) {
    const lines = topSpenders.slice(0, 5).map((r) => {
      const name = r.publisherName ? ` (${r.publisherName})` : '';
      return `• \`${r.publisherId}\`${name} / ${r.dsp} — DSP Spend $${Math.round(r.dspSpend ?? 0).toLocaleString()} — Spend ${fmtPct(r.spendDiscrepancyPct)}`;
    });
    blocks.push({ type: 'divider' });
    blocks.push({ type: 'section', text: { type: 'mrkdwn', text: '📋 *Top 20 Spenders by DSP Partner Spend*\n' + lines.join('\n') } });
  }

  if (hasHighlights) {
    const lines = highlights.slice(0, 10).map((r) => {
      const name = r.publisherName ? ` (${r.publisherName})` : '';
      return `• \`${r.publisherId}\`${name} / ${r.dsp} — *Spend ${fmtPct(r.spendDiscrepancyPct)}* (DSP Spend $${Math.round(r.dspSpend ?? 0).toLocaleString()})`;
    });
    blocks.push({ type: 'divider' });
    blocks.push({ type: 'section', text: { type: 'mrkdwn', text: `⚠️ *Highlights (>±${th.toFixed(0)}% Spend or Imps Discrepancy)*\n` + lines.join('\n') } });
  }

  const publishers = new Set(rows.map((r) => r.publisherId)).size;
  const dsps = new Set(rows.map((r) => r.dsp)).size;
  blocks.push({
    type: 'context',
    elements: [{ type: 'mrkdwn', text: `Publishers: ${publishers} | DSPs: ${dsps} | Full report in email` }],
  });

  return blocks;
}
